version: '3.3'
services:
  db:
    image: "mysql:latest"
    environment:
      MYSQL_DATABASE: ${DB_SERVER_DATABASE}
      MYSQL_USER: ${DB_SERVER_USERNAME} 
      MYSQL_PASSWORD: ${DB_SERVER_PASSWORD} 
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
     - "./db:/docker-entrypoint-initdb.d"
  www:
    build: ./
    volumes:
     - "./:/var/www/html"
    ports:
     - "8080:80"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
     - "8001:80"
    # environment:
    #  - PMA_HOST=db
    #  - PMA_PORT=3306
    depends_on:
      - db
